# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Nano Processor My Files/Nano/nano processor/nano processor.cache/wt} [current_project]
set_property parent.project_path {D:/Nano Processor My Files/Nano/nano processor/nano processor.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo {d:/Nano Processor My Files/Nano/nano processor/nano processor.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/Add_Sub_4.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/D_FF.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/Decoder_2_to_4.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/Decoder_3_to_8.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/Components/FA.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/Components/HA.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/Components/LUT_16_7.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/MUX_2_way_4_bit.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/new/MUX_8_way_4_bit.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/new/PCounter_U.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/Program_ROM.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/Reg.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/Slow_Clk.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/Downloads/instruction_decoder.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/imports/component/register_bank.vhd}
  {D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/sources_1/new/Nano_Processor.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/constrs_1/imports/component/Nanoprocessor.xdc}}
set_property used_in_implementation false [get_files {{D:/Nano Processor My Files/Nano/nano processor/nano processor.srcs/constrs_1/imports/component/Nanoprocessor.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Nano_Processor -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Nano_Processor.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Nano_Processor_utilization_synth.rpt -pb Nano_Processor_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
